name: CI - PREPROD-ASSET-WORKER
on:
  push:
    branches: [dev]

jobs:
  deploy:
    environment: preprod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: build asset worker
        run: |
          npm i
          npm run build
      - name: build asset-worker image
        run: docker build -t mo29172/lghorba_asset_worker:v${{ github.run_number }} -f docker/worker/Dockerfile .
      - name: push asset-worker image to docker hub
        run: |
          docker push mo29172/lghorba_asset_worker:v${{ github.run_number }}
      - name: update asset-worker deployment file version
        run: |
          sed -i -e"s/:latest/:v${{ github.run_number }}/" docker/k8s/asset-worker-deployment.yaml


      - name: copy k8s files via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'docker/k8s/asset-worker-cluster-ip-service.yaml,docker/k8s/asset-worker-deployment.yaml,docker/k8s/asset-worker-hpa.yaml,'
          target: '/srv/k8s/asset-worker'
          strip_components: 2
          timeout: 5m

      - name: apply k8s files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SECOND_USER }}
          password: ${{ secrets.SERVER_SECOND_USER_PASSWORD }}
          script: |
            kubectl delete secret asset-worker-envs --ignore-not-found=true
            kubectl create secret generic asset-worker-envs \
            --from-literal NODE_ENV=${{ secrets.NODE_ENV }} \
            --from-literal APP_URL=${{ secrets.APP_URL }} \
            --from-literal BACK_PORT=${{ secrets.BACK_PORT }} \
            --from-literal TYPEORM_HOST=${{ secrets.TYPEORM_HOST }} \
            --from-literal TYPEORM_PORT=${{ secrets.TYPEORM_PORT }} \
            --from-literal TYPEORM_USERNAME=${{ secrets.TYPEORM_USERNAME }} \
            --from-literal TYPEORM_PASSWORD=${{ secrets.TYPEORM_PASSWORD }} \
            --from-literal TYPEORM_DATABASE=${{ secrets.TYPEORM_DATABASE }} \
            --from-literal GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }} \
            --from-literal GCS_PROJECT_ID=${{ secrets.GCS_PROJECT_ID }} \
            --from-literal GCS_CLIENT_EMAIL=${{ secrets.GCS_CLIENT_EMAIL }} \
            --from-literal GCS_PRIVATE_KEY_ID=${{ secrets.GCS_PRIVATE_KEY_ID }} \
            --from-literal GCS_PRIVATE_KEY=${{ secrets.GCS_PRIVATE_KEY }} \
            --from-literal REDIS_HOST=${{ secrets.REDIS_HOST }} \
            --from-literal REDIS_PORT=${{ secrets.REDIS_PORT }} \
            --from-literal REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
            --from-literal REDIS_DB=${{ secrets.REDIS_DB }}
            kubectl apply -f /srv/k8s/asset-worker
            minikube addons enable ingress
            echo ${{ secrets.SERVER_SECOND_USER_PASSWORD }} | sudo -S systemctl restart nginx
            echo y | docker exec -i minikube docker system prune -a --volumes
            